name: Change Tracking Marker
on:
  push:
    branches: [ main ]

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: Automatic Tagging of Releases
            id: increment-git-tag
            run: |
              bash ./build/git_update.sh -v major
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.1.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
          version: ${{ steps.increment-git-tag.outputs.git-tag }}
          user: "${{ github.actor }}"
          description: ${{ github.event.head_commit.message }}